### ISSUE TITLE
Requirements checklist for MVP

### ISSUE THREAD

**Issue by gdiasdasilva** [Cineclub/cineclub#53]
- [x] Rails update to latest version 6.1.3
- [x] User confirmation after registration
  - We could do this either through a confirmation e-mail or manually in a first phase
- [x] Add authorization policies for all eligible actions
- [ ] Add error monitoring tool for production environments 
  - [Honeybadger](https://www.honeybadger.io/plans/) allows up to 3 users for free
- [x] Any user, in any of their teams (later, we'll enforce a fairness rule, but for now let's do it like this), can pick THE movie for that round. There's only one, we may or may not allow to replace; up to debate
- [x] Fix round number in views (currently using id)
- [x] Add `admin` flag to the user model (this flag can be used to give super-user permissions, like editing protected data, etc.)
- [ ] Improve homepage's "copy"
- [ ] [to evaluate further] asynchronous/background job processing (namely for sending confirmation e-mail)
- [ ] Add privacy policy page
- [ ] Configure logging. Study options. By this I mean writing creating meaningful messages for several events, like HTTP requests made to the outside, execution stages of interactors, etc. The logger should write relevant tags for each line like HTTP request UUID, timestamp, etc. This is to be later integrated with Papertrail or similar.
- [ ] Control rounds' membership: users that belong to the round (initially the user which creates it, its only member) can invite other users, only then can they join. (I think in this phase we don't need to think about "team administrators" different than other members. This goes along the model of users are well-behaved **inside their teams** (so we only need to protect other teams).

**Comment by gdiasdasilva** [comment]
Admin flag added in #59.

**Comment by gdiasdasilva** [comment]
User confirmation e-mail added in #56.

**Comment by gdiasdasilva** [comment]
Honeybadger added in #63.

**Comment by gdiasdasilva** [comment]
Picking the movie for a round added in #61.

**Comment by ruiccarvalho** [comment]
Edited the original issue text to replace Rails 6.1.1 with 6.1.3, as that is the current latest version.

**Comment by ruiccarvalho** [comment]
Added a bullet for setting up "advanced" logging.

**Comment by gdiasdasilva** [comment]
> Any user, in any of their teams (later, we'll enforce a fairness rule, but for now let's do it like this), can pick THE movie for that round. There's only one, we may or may not allow to replace; up to debate

I've checked this bullet, since we already allow users to set AND edit the movie for a round.

**Comment by gdiasdasilva** [comment]
Fix round number in views (currently using id) implemented in #70.

**Comment by gdiasdasilva** [comment]
Rails update to latest version 6.1.4.1 in #79.

**Comment by gdiasdasilva** [comment]
Adding invitations in #72.

**Comment by gdiasdasilva** [comment]
I think the last bullet should be about teams and not rounds, @ruiccarvalho 🤔.

> Control **teams**' membership: users that belong to the **team** (initially the user which creates it, its only member) can invite other users, only then can they join. (I think in this phase we don't need to think about "team administrators" different than other members. This goes along the model of users are well-behaved inside their teams (so we only need to protect other teams).

If so, this is being implemented in #72.
